apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engine-api-9351
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/engine-api-9351
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
